# Generated by Django 4.1 on 2022-09-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='yosh',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
