# Generated by Django 4.1 on 2022-09-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_student_bitiruvchi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muallif',
            name='yosh',
        ),
    ]
